!/var/log/audit/audit\.log$
!/var/log/audit
!/var/log/sysstat
!/root/lab-hardening
!/home/adminlab/lab-hardening
!/var/log/audit/audit.log$
!/var/log/audit
!/var/log/sysstat
!/var/log/journal
!/var/log/lynis
!/var/log/lynis.log
!/var/log/lynis-report.dat
!/var/lib/apt/lists
!/var/lib/apt/periodic
!/var/cache/apt
!/var/cache/swcatalog
!/var/lib/swcatalog
!/var/lib/ubuntu-advantage
!/var/lib/update-notifier
!/var/lib/PackageKit
!/run
!/home/adminlab/lab-hardening
!/root/lab-hardening
