template(name="SecurityLogs" type="string"
  string="/var/log/remote/security/%HOSTNAME%-%$YEAR%%$MONTH%%$DAY%.log")

if ($hostname == 'vm1-objetivo') then {
  action(type="omfile" dynaFile="SecurityLogs")
}
